// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol KeysGlobalProtocol {
    var appId: String { get }
}

public protocol KeysEnvironmentProtocol {}
